# Generated by Django 3.1.7 on 2021-03-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('ListingId', models.AutoField(primary_key=True, serialize=False)),
                ('ListingName', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=2)),
                ('Description', models.CharField(max_length=500)),
                ('Thumbnail', models.CharField(max_length=100)),
                ('Img_one', models.CharField(max_length=100)),
                ('Img_two', models.CharField(max_length=100)),
                ('Img_three', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceID', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorId', models.AutoField(primary_key=True, serialize=False)),
                ('VendorName', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=20)),
                ('Profilepic', models.CharField(max_length=100)),
            ],
        ),
    ]
