# Generated by Django 3.1.7 on 2021-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0002_auto_20210401_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
