# Generated by Django 3.1.7 on 2021-04-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0003_auto_20210403_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Thumbnail',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
