# Generated by Django 3.1.7 on 2021-04-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0004_auto_20210403_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Thumbnail',
            field=models.CharField(max_length=100),
        ),
    ]
